#!/usr/bin/env python3

"""
Usage: python3 make_merged_teachables.py SOURCE_DIR

Build a C-header defining the set of teachable moves for each configured-on
species-family based on the learnable moves defined in SOURCE_DIR/all_learnables.json.
"""

from itertools import chain
from textwrap import dedent

import json
import pathlib
import re
import sys
import typing


CONFIG_ENABLED_PAT = re.compile(r"^#define P_LEARNSET_HELPER_TEACHABLE\s+(?P<cfg_val>[^ ]*)", flags=re.MULTILINE)
TM_LITERACY_PAT = re.compile(r"^#define P_TM_LITERACY\s+GEN_(?P<cfg_val>[^ ]*)", flags=re.MULTILINE)
ALPHABETICAL_ORDER_ENABLED_PAT = True
SNAKIFY_PAT = re.compile(r"(?!^)([A-Z]+)")


def enabled() -> bool:
    with open("./include/config/pokemon.h", "r") as cfg_pokemon_fp:
        cfg_pokemon = cfg_pokemon_fp.read()
        cfg_defined = CONFIG_ENABLED_PAT.search(cfg_pokemon)

        return (
            cfg_defined is not None
            and cfg_defined.group("cfg_val") in ("TRUE", "1")
        )


def extract_tm_litteracy_config() -> bool:
    config = False
    with open("./include/config/pokemon.h", "r") as cfg_pokemon_fp:
        cfg_pokemon = cfg_pokemon_fp.read()
        cfg_defined = TM_LITERACY_PAT.search(cfg_pokemon)
        if cfg_defined:
            cfg_val = cfg_defined.group("cfg_val")
            if ((cfg_val == "LATEST") or (int(cfg_val) > 6)):
                config = True
    return config


def prepare_output(all_learnables, special_movesets, repo_teaching_types, header):
    """
    Build the file content for teachable_learnsets.h.
    """

    tm_litteracy_config = extract_tm_litteracy_config()

    new = header + dedent("""\
    static const u16 sNoneTeachableLearnset[] = {
        MOVE_UNAVAILABLE,
    };

    """)

    for species_data in repo_teaching_types:
        if isinstance(species_data, str):
            new += species_data
            continue

        species = species_data["name"]
        teaching_type = species_data["teaching_type"]
        species_upper = SNAKIFY_PAT.sub(r"_\1", species).upper()

        learnables = set(all_learnables.get(species_upper, []))

        if teaching_type == "ALL_TEACHABLES":
            learnables |= set(special_movesets["universalMoves"])
            learnables -= set(special_movesets["signatureTeachables"])
        else:
            if teaching_type != "TM_ILLITERATE":
                learnables |= set(special_movesets["universalMoves"])
            elif not tm_litteracy_config:
                learnables -= set(special_movesets["universalMoves"])

        if species_upper == "TERAPAGOS":
            learnables.discard("MOVE_TERA_BLAST")

        moves = sorted(learnables)

        new += f"static const u16 s{species}TeachableLearnset[] = "
        new += "{\n"

        for move in moves:
            new += f"    {move},\n"

        new += (
            "    MOVE_UNAVAILABLE,\n"
            "};\n\n"
        )

    return new


def prepare_header():
    return dedent("""\
//
 // DO NOT MODIFY THIS FILE! It is auto-generated by tools/learnset_helpers/make_teachables.py
//
""")


def build_all_learnables(source_data):
    all_learnables = {}

    for species, learnset in source_data.items():
        moves = set()

        for move in learnset.get("LevelMoves", []):
            moves.add(move["Move"])

        for move in learnset.get("PreEvoMoves", []):
            moves.add(move)

        for move in learnset.get("EggMoves", []):
            moves.add(move)

        for move in learnset.get("TMMoves", []):
            moves.add(move)

        for move in learnset.get("TutorMoves", []):
            moves.add(move)

        all_learnables[species] = sorted(moves)

    return all_learnables


def main():
    if not enabled():
        quit()

    if len(sys.argv) != 2:
        print("Invalid number of arguments", file=sys.stderr)
        print(__doc__, file=sys.stderr)
        quit(1)

    SOURCE_DIR = pathlib.Path(sys.argv[-1])
    SOURCE_TEACHING_TYPES_JSON = SOURCE_DIR / "all_teaching_types.json"
    assert SOURCE_TEACHING_TYPES_JSON.exists(), f"{SOURCE_TEACHING_TYPES_JSON=} does not exist"
    assert SOURCE_TEACHING_TYPES_JSON.is_file(), f"{SOURCE_TEACHING_TYPES_JSON=} is not a file"

    with open(SOURCE_TEACHING_TYPES_JSON, "r") as source_fp:
        repo_teaching_types = json.load(source_fp)

    porymoves_files = ["usum", "swsh", "sv", "za"]
    all_learnables = {}

    for file in porymoves_files:
        SOURCE_PORYMOVES_JSON = SOURCE_DIR.parent / f"porymoves_files/{file}.json"

        assert SOURCE_PORYMOVES_JSON.exists(), f"{SOURCE_PORYMOVES_JSON=} does not exist"
        assert SOURCE_PORYMOVES_JSON.is_file(), f"{SOURCE_PORYMOVES_JSON=} is not a file"

        with open(SOURCE_PORYMOVES_JSON, "r") as source_fp:
            source_data = json.load(source_fp)

        new_learnables = build_all_learnables(source_data)

        for species, moves in new_learnables.items():
            if species not in all_learnables:
                all_learnables[species] = []

            all_learnables[species].extend(moves)

            all_learnables[species] = sorted(set(all_learnables[species]))

    with open("src/data/pokemon/special_movesets.json", "r") as file:
        special_movesets = json.load(file)

    with open("./src/data/pokemon/all_learnables.json", "w") as output_fp:
        json.dump(all_learnables, output_fp, indent=2, sort_keys=True)

    header = prepare_header()
    content = prepare_output(all_learnables, special_movesets, repo_teaching_types, header)

    with open("./src/data/pokemon/teachable_learnsets.h", "w") as teachables_fp:
        teachables_fp.write(content)


if __name__ == "__main__":
    main()
