#!/usr/bin/env python3

"""
Usage: python3 make_tutor_array.py
Helper script to run before ROM compilation to create an empty gTutorMoves[] array.
"""

from textwrap import dedent

def main():
    """
    Generate gTutorMoves[].
    """
    header = dedent("""\
        // DO NOT MODIFY THIS FILE! It is auto-generated by tools/learnset_helpers/make_tutor_array.py
        // It is not needed by tutor moves relearner anymore due to merged teachables.

        const u16 gTutorMoves[] = {
            MOVE_UNAVAILABLE
        };
    """)

    with open("./src/data/tutor_moves.h", "w") as f:
        f.write(header)


if __name__ == "__main__":
    main()
